version: 2

updates:

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "- r "
  groups:
    approvals:
        patterns:
          - approvaltests
          - approvals-utilities


- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "- r "

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "- e "
