name: Update Python Dependencies

on:
  schedule:
    # Runs at 05:00 UTC every Monday
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git checkout -b update-dependencies-${{ github.run_id }}
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b update-python-dependencies-${{ github.run_id }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pip-tools
    - run: pip-compile --upgrade --output-file=constraints.txt requirements.txt
    - name: Commit updates
      run: |
        git commit -am "- r Update Python dependencies"
    - name: Create Pull Request
      run: |
        gh pr create -B main --fill
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
