name: Update Python Dependencies

on:
  schedule:
    # Runs at 05:00 UTC every Monday
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update dependencies
      run: |
        pip-compile --upgrade

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit updates
      run: |
        git commit -am "- r Update Python dependencies" || echo "No changes to commit"

    - name: Create Pull Request
      run: |
        gh pr create -B main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
